### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Wengiel31** [saeedvaziry/spotdl#1]
npm install, then node server gives:

``` javascript App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
Emitted 'error' event at:
    at RedisClient.<anonymous> (C:\Users\Wengi\Desktop\spotdl-master\node_modules\kue\lib\redis.js:65:13)
    at RedisClient.emit (events.js:203:13)
    at RedisClient.on_error (C:\Users\Wengi\Desktop\spotdl-master\node_modules\kue\node_modules\redis\index.js:401:14)
    at Socket.<anonymous> (C:\Users\Wengi\Desktop\spotdl-master\node_modules\kue\node_modules\redis\index.js:279:14)
    at Socket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

**Comment by saeedvz** [comment]
Did you created .env file on project root?
There is `.env.example`. You can rename it to `.env` and modify content

**Comment by Wengiel31** [comment]
I did not. That might be the problem thanks for help <3!

**Comment by Wengiel31** [comment]
> Did you created .env file on project root?
> There is `.env.example`. You can rename it to `.env` and modify content

Wall, no I didn't, BUT after doing it I get the same error :/

**Comment by saeedvz** [comment]
Make sure that you have python3 and https://github.com/ritiek/spotify-downloader installed

**Comment by saeedvz** [comment]
Also install `redis-server` on your OS

**Comment by Wengiel31** [comment]
I didn't know that I had to install Redis :P . Now everything is working.

For others:

Don't forget to edit the ".env" file afterwards and set "REDIS_URL" port to the one that You've chose while installing Redis.

**Comment by saeedvz** [comment]
Readme updated.
